const PERMISSIONS = {
    ANY: 'ANY',
    USER: 'USER',
    SUPER_USER: 'SUPER_USER',
    RENT_ENTERPRISE:'RENT_ENTERPRISE',
    TALLER_ENTERPRISE:'RENT_ENTERPRISE'
}

module.exports = {
    PERMISSIONS
}